print("https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+pl_name,hostname,discoverymethod,disc_year,sy_pnum,sy_snum,pl_orbper,pl_orbsmax,pl_rade,pl_radj,pl_bmasse,pl_bmassj,pl_orbeccen,pl_eqt,pl_insol,st_teff,st_rad,st_mass,st_met,st_logg,sy_dist,sy_vmag+from+pscomppars&format=csv")
print("Please download this file and save in Downloads")
import pandas as pd
A=input('What is username?')
df = pd.read_csv(f"C:/Users/{A}/Downloads/data.csv")
df = df.fillna('Unknown')
print('Composing DataFrame and Importing Libraries')
import pymysql
import sqlalchemy
print('please create database "Analysis" in MySQL')
from sqlalchemy import create_engine
U=input("Username,root:")
L=input("localhost:3306:")
P=input("SQL password:")
engine = create_engine(f"mysql+pymysql://{U}:{P}@{L}/analysis")
df.to_sql('PlanetData',engine,if_exists='append',index=False)
print(df.notnull().sum())
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()
X=input('x-parameter:')
Y=input('y-parameter:')
print('fetching database')
import matplotlib.pyplot as plt
df1=pd.read_sql_query(f"Select `{X}`,`{Y}` From PlanetData WHERE {X}!='Unknown' AND {Y}!='Unknown'",engine)
df1=df1.astype(float)
df1.plot(x=X,y=Y,kind='scatter')
plt.xscale('log')
plt.yscale('log')
plt.show()

